### ISSUE TITLE
Use tokens of MoreGreetings Extension

### ISSUE THREAD

**Issue by mmgit** [systopia/de.systopia.donrec#110]
Hi,
it would be nice to have access to the data of the More Greetings extension for using in the donrec templates. We use More Greetings to create our addressee and greeting fields. Or is it possible to do api calls in a template?

Regards
Marcus

**Comment by jensschuppe** [comment]
Since the donrec template does not use CiviCRM tokens, but Smarty variables, the MoreGreetings custom fields do not seem to be available, that's true. Maybe making available all contact tokens would be desirable.

In the meantime, Performing API calls in donrec templates is what we've been doing for retrieving custom field values. An example:

```smarty
{crmAPI var="cf_addressee_name" entity="CustomField" action="getsingle" version="3" custom_group_id="more_greetings_group" name="greeting_field_4"}
{capture assign="addressee_name"}custom_{$cf_addressee_name.id}{/capture}
{* Do the same for more custom fields. *}
{capture assign="contributor_extra_return"}{$addressee_name},{$another_field_name},{$yet_another_field_name}{/capture}
{crmAPI var="contributor_extra" entity="Contact" action="getsingle" version="3" id="$contributor_id" return="$contributor_extra_return"}
```
 Usage:

```smarty
<p>{$contributor_extra.$addressee_name}</p>
```

Ugly, but powerful. Feel free to file another issue or PR for including all contact tokens in donrec templates by default.

**Comment by bjendres** [comment]
Keep in mind, that there was a reason we wouldn't allow CiviCRM Tokens in the receipt template: if the tokens change, a future copy of the of receipt would differ from the the original. This could lead to trouble with some tax authorities; in particular some of the German ones.

Using the API to pull data would obviously cause the same potential issues.

**Comment by jensschuppe** [comment]
Thanks, @bjendres, that's of course true. I remember discussing an approach with user-defined "variables" per profile, which could use contact token values and would be explicitly stored with the receipt to avoid changes.
