### ISSUE TITLE
upgrade from v1.8, what version to choose 2.0-x or 2.1-x?

### ISSUE THREAD

**Issue by sluc23** [systopia/de.systopia.donrec#111]
We are starting the planning an upgrade from version 1.8, and there are 2 versions being developed a the same time, 2.0 and 2.1.

@bjendres  I haven't seen any roadmap or docs about the different features between versions, but in this case what do you recommend to upgrade to?

cheers!

**Comment by jensschuppe** [comment]
Version 2.1 will have (at least) the following extra features (compared to 2.0):
* [#96] Custom bounce Handling - by @pbatroff
* [#101] Unlock settings not applied correctly due to ID mismatches - by @jensschuppe
* [#102] Add OVERWRITE to zip mode - by @zonradkuse
* [#106] Update legal notice in German default template - by @jojowork

If you don't need any of them, install 2.0-beta3, which is "more stable" than 2.1-alpha1.

**Comment by sluc23** [comment]
> Version 2.1 will have (at least) the following extra features (compared to 2.0):
> 
>     * [#96] Custom bounce Handling - by @pbatroff
> 
>     * [#101] Unlock settings not applied correctly due to ID mismatches - by @jensschuppe
> 
>     * [#102] Add OVERWRITE to zip mode - by @zonradkuse
> 
>     * [#106] Update legal notice in German default template - by @jojowork
> 
> 
> If you don't need any of them, install 2.0-beta3, which is "more stable" than 2.1-alpha1.

cool, thanks @jensschuppe fir the info!

**Comment by zonradkuse** [comment]
I think 2.1-alpha1 does not yet contain #102. We tried updating to 2.1-alpha1 but had to manually apply the change again. Looking forward to 2.1, though! :)

**Comment by jensschuppe** [comment]
You are right, it has been merged after 2.1-alpha1 was tagged. This also applies for #101 and #106, which leaves 2.1-alpha1 with #96 only. Sorry, I copied the release draft which included all merged changes.

If you need the other features, you can install the current master at 12f7c3c84030582878af69879e8278a1a7a357c5.
