### ISSUE TITLE
Select currency

### ISSUE THREAD

**Issue by systopia** [systopia/de.systopia.donrec#12]
Currently, the currency is hard-coded to EUR, but there should be dropdown at the beginning (next to the date selector) that lets you pick the currency to be used.

**Comment by elcapo** [comment]
Hello Björn, long time no see! I'm back working for CiviCRM, now with Ixiam. Alejandro asked me to take a look at the receipts extension because we are talking with a few people whom probably will use it.

I still haven't tested it enough to make a PR but, as you can see in the related commits above, I've been working on the extension to make it work for other currencies. What these commits are doing is:

- Add a currency selector below the profile and time selector.
- Filtering the contributions to include in the receipt only the ones of the selected currency.
- Modifying a few templates so the currency is properly shown ($5.00 instead of 5,00€ and so on).

I'll let you know when the changes are ready. Just wanted you to know I'm working on it. Feedback is welcome.

**Comment by systopia** [comment]
Hi @elcapo! Good to hear from you. Sorry for the late response, I was on holiday. 

That initiative sounds great, let me know when you have any questions.

**Comment by systopia** [comment]
released with ``1.6-beta1``
