### ISSUE TITLE
Profile copying broken

### ISSUE THREAD

**Issue by mielert** [systopia/de.systopia.donrec#36]
After clicking the save button in "civicrm/admin/setting/donrec" the copied profile disappears.

CiviCRM 4.7.8 
Part of #34

**Comment by systopia** [comment]
I couldn't reproduce this on CiviCRM 4.6, but I could on 4.7. Therefore this is a compatibility problem, see #34.

**Comment by systopia** [comment]
So it turns out that CiviCRM 4.7 has dropped the {{group_name}} from the settings altogether, and the profile system was heavily relying on that. So the whole profile system had to be refactored, see https://github.com/systopia/de.systopia.donrec/tree/dev_34

We'll put some more things in 1.4 and then ask for help with testing :)
